[
{"name":"雷蒙","url": "https://agit.ai/n3rd/N3RD/raw/branch/master/JN/tv.txt"},
{"name":"全球","url": "https://ghproxy.com/raw.githubusercontent.com/fanmingming/live/main/tv/m3u/global.m3u"},
{"name":"4K8K","url": "https://ghproxy.com/https://raw.githubusercontent.com/youshandefeiyang/IPTV/main/main/IPTV.m3u"},
{"name":"蜀小果","url": "https://ghproxy.com/https://raw.githubusercontent.com/youshandefeiyang/IPTV/main/main/sxg.m3u"},
{"name":"itouch","url": "https://ghproxy.com/https://raw.githubusercontent.com/youshandefeiyang/IPTV/main/main/itouch.m3u"},
{"name":"重庆有线","url": "https://ghproxy.com/https://raw.githubusercontent.com/youshandefeiyang/IPTV/main/main/cqyx.m3u"},
{"name":"YSLive","url": "https://agit.ai/Yoursmile7/TVBox/raw/branch/master/live.txt"},
{"name":"肥羊精选","url": "https://telegram-feiyangdigital.v1.mk"},
{"name":"APTV","url": "https://ghproxy.com/https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/aptv-playback.m3u"},
{"name":"爱尚","url": "https://ghproxy.com/https://raw.githubusercontent.com/youshandefeiyang/IPTV/main/main/aishang.m3u"},
{"name":"百事通","url": "https://telegram-feiyangdigital.v1.mk/bestv.m3u"},
{"name":"ChinaTV","url": "https://ghproxy.com/https://raw.githubusercontent.com/whpsky/iptv/main/chinatv.m3u"},
{"name":"搜集","url": "https://ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u"},
{"name":"FMLive","url": "http://home.jundie.top:81/Cat/tv/live.txt"},
{"name":"斗鱼直播","url": "https://ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/yu.m3u"},
{"name":"虎牙直播","url": "https://ghproxy.com/https://raw.githubusercontent.com/YanG-1989/m3u/main/ya.m3u"},
{"name":"ZHGIPTV","url": "https://ghproxy.com/https://raw.githubusercontent.com/zhanghongguang/zhanghongguang.github.io/main/myiptv.m3u"},
{"name":"ZHGPlaylist","url": "https://ghproxy.com/https://raw.githubusercontent.com/zhanghongguang/zhanghongguang.github.io/main/playlist.m3u"},
{"name":"电台","url": "https://ghproxy.com/https://raw.githubusercontent.com/goolguy007/radioer/main/TVradio"},
{"name":"FTYLive","url": "https://agit.ai/fantaiying/fty/raw/branch/master/live.txt"}
]