var rule = {
	title: '飞云[V2]', 
	host: 'http://i.xn--z7x900a.love:63',
	homeUrl:'/api.php/provide/vod?ac=detail',
	url: '/api.php/provide/vod/?t=fyclassfyfilter&ac=detail&pg=fypage',
	filter_url:'&class={{fl.class}}&area={{fl.area}}&lang={{fl.lang}}&year={{fl.year}}&by={{fl.by}}',
	filter: {
		"1":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""}]},{"key":"lang","name":"语言","value":[{"n":"全部","v":""}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""}]}],
		"2":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""}]},{"key":"lang","name":"语言","value":[{"n":"全部","v":""}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""}]}],
		"3":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""}]},{"key":"lang","name":"语言","value":[{"n":"全部","v":""}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""}]}],
		"4":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""}]},{"key":"lang","name":"语言","value":[{"n":"全部","v":""}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""}]}]
	},
	detailUrl:'/api.php/provide/vod?ac=detail&ids=fyid',
	searchUrl: 'api.php/provide/vod?ac=detail&wd=**',
	searchable: 2,
	quickSearch: 0,
	filterable: 0,
	headers:{'User-Agent':'Mozilla/5.0'},
	timeout:5000,
	class_name:'电影&电视剧&动漫&综艺',
	class_url:'1&2&3&4',
	play_parse:true,
    lazy:'js:if(/Feiyun/.test(input)){let purl=request("https://jx.g2.pub/?url="+input);input={jx:0,url:JSON.parse(purl).url,parse:0}}else{input}', 

    limit:6,
	推荐:'*',
	一级:'json:list;vod_name;vod_pic;vod_remarks;vod_id',
	二级:'js:try{let html=request(input);print(html);html=JSON.parse(html);let node=html.list[0];VOD={vod_id:node["vod_id"],vod_name:node["vod_name"],vod_pic:node["vod_pic"],type_name:node["vod_class"],vod_year:node["vod_year"],vod_area:node["vod_area"],vod_remarks:node["vod_remarks"],vod_actor:node["vod_actor"],vod_director:node["vod_director"],vod_content:node["vod_content"].strip(),vod_play_url:node["vod_play_url"],vod_play_from:node["vod_play_from"]};}catch(e){log("获取二级详情页发生错误:"+e.message)}',
	搜索:'*',
}